### ISSUE TITLE
Collaboration / Integration

### ISSUE THREAD

**Issue by nomisRev** [icemachined/kafka-kotlin-native#2]
Hey @icemachined, and all other contributors,

Thanks for this amazing effort 🙏 It's really awesome seeing support for something like this in Kotlin 🙌
Over the summer I started a Kafka streaming project, similar to [reactor-kafka](https://github.com/reactor/reactor-kafka) and [Alpakka Kafka](https://github.com/akka/alpakka-kafka) but instead of respectively Project Reactor and Akka build on top of KotlinX Coroutines Flow. The project lives [here](https://github.com/nomisRev/kotlin-kafka).

Since the JVM implementation is almost finished, I was hoping to also support Kotlin JS and Kotlin Native in the future but before pulling in your library and trying to integrate it using `expect/actual` I wanted to reach out and ask what your ambitions were with this project. I don't want to create competing libraries, or conflict in the Kotlin MPP eco-system. Additionally, this project clearly took a lot of amazing work. Big kudos to everyone involved!

So my question, would there be interest in create a Kafka 4 Kotlin OSS org on Github where we could group these efforts as a neutral space for all different Kafka efforts happening atm in Kotlin? Do you mind if I depend on this library to provide a Kotlin Native implementation for the kafka-kotlin streaming project?

Ultimate goal would be to have some Kotlin MPP facade for Kafka, and ideally expose integrations for Ktor, or other Kotlin MPP frameworks.

What do you think? Again, thanks for brining such awesome library to the Kotlin eco-system 🎉

**Comment by orchestr7** [comment]
Oh, that sounds amazing! Idea about making a committee is awesome, but I think that this repo still should remain under the personal control of @icemachined as he is an author of the idea.

May be it is possible to use this library as a core dependency in a common interface?

**Comment by icemachined** [comment]
Hi @nomisRev !
Yes, sounds great! We are going to use this client in our project saveourtool to build kotlin native cloud services using kafka and are interested in this library is widely used by community also. So we are opened to any collaborations and don't mind any dependencies of course. We will be happy to help with an adoption or any bugfixes.
As for separate org I agree with Andrey, don't see any need in this, i'd prefer to keep it in my personal space at least for now,, the same as librdkafka is kept in personal space of Magnus Edenhill and everybody use it.

**Comment by nomisRev** [comment]
Hey @icemachined & @akuleshov7!

Thanks for the reply! Not creating an org is fine ☺️ It's something that has happend in the past with other projects I am involved on, so I wanted to know your thoughts.

> So we are opened to any collaborations and don't mind any dependencies of course. We will be happy to help with an adoption or any bugfixes.

Thank you, I will rely on your great work to make Kotlin Native a possible target for the library I've worked on. Going to close this ticket, but anyone feel free to leave other suggestions or remarks 👍
